apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 discovery-server {{ .Values.service.discoveryServer.port }}; do echo waiting for discovery-server; sleep 2; done;"
      containers:
        - name: genai-service
          image: "{{ .Values.image.genaiService.repository }}:{{ .Values.image.genaiService.tag }}"
          ports:
            - containerPort: {{ .Values.service.genaiService.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:{{ .Values.service.discoveryServer.port }}/eureka/
            - name: SPRING_ZIPKIN_TRACING_ENDPOINT
              value: http://tracing-server:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: genai-service
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: ${spring.application.name}:${random.uuid}
            - name: CONFIG_SERVER_URL
              value: http://config-server:{{ .Values.service.configServer.port }}
            - name: AZURE_OPENAI_KEY
              value: ${AZURE_OPENAI_KEY:your_default_azure_key}
            - name: AZURE_OPENAI_ENDPOINT
              value: ${AZURE_OPENAI_ENDPOINT:http://default-azure-endpoint}
            - name: OPENAI_API_KEY
              value: test
            - name: EUREKA_INSTANCE_HOSTNAME
              value: genai-service
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  selector:
    app: genai-service
  ports:
    - port: {{ .Values.service.genaiService.port }}
      targetPort: {{ .Values.service.genaiService.port }}
